In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors.
### Creating tensors.

In [ ]:
# Using Scalar.
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int.
scalar.item()

7

In [ ]:
# Using vectors.
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [10, 11, 12]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Creating Random tensors

Random tensors are important because the way neural network learns is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5191, 0.5853, 0.6106, 0.7462],
        [0.1722, 0.6035, 0.0012, 0.7663],
        [0.8903, 0.5058, 0.7251, 0.4376]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.8501, 0.9451, 0.3533, 0.0527],
         [0.0494, 0.0616, 0.7522, 0.8747],
         [0.9305, 0.8359, 0.7802, 0.8659]],

        [[0.9532, 0.3799, 0.9388, 0.5942],
         [0.2814, 0.9643, 0.7160, 0.2730],
         [0.7806, 0.3651, 0.2348, 0.0736]],

        [[0.9934, 0.4722, 0.7185, 0.8979],
         [0.7055, 0.2082, 0.9525, 0.9944],
         [0.6674, 0.7374, 0.6801, 0.8904]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor.
random_img_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels(R,G,B)
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros.
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones.
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype # defautl data type.

torch.float32

### Tensor in range and tensors-like

In [ ]:
# Use torch.range() and get deprecated msg use torch.arange()
elements_in_range = torch.arange(start=1,end=11, step=1)
elements_in_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=elements_in_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes.
**Note:**Tensor datatypes is one of the 3 big errors:
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device.

In [ ]:
# Default float data type in python is float 32
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None)
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.float16)
float_32_tensor.dtype

torch.float16

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # What dataype is the tensor.
                               device = None, # What device is the tensor on.
                               requires_grad=False) # Whether or not to track gradients with this tensors operations.
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# Converting float 32 tensor into float 16 tensor.
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Example: multiplying two different data type tensors.
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting informations from tensor. [Tensor Attributes]
1. Tensors not right datatype - to get datatypes from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get datatypes from a tensor, can use `tensor.shape`
3. Tensors not on the right device. - to get datatypes from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor.
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8398, 0.1908, 0.3634, 0.3797],
        [0.8751, 0.7173, 0.7571, 0.5665],
        [0.4010, 0.4034, 0.2812, 0.4758]])

In [ ]:
# Find details about tensor.
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor is on: {some_tensor.device}")

tensor([[0.8398, 0.1908, 0.3634, 0.3797],
        [0.8751, 0.7173, 0.7571, 0.5665],
        [0.4010, 0.4034, 0.2812, 0.4758]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Tensor is on: cpu


### Manipulating Tensors: (Tensor operations)

Tensor operations include:
* Addition.
* Subtraction.
* Multiplication.
* Division.
* Matrix Multiplication.

In [ ]:
# Create tensor and add 10.
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch in-built functions
torch.mul(tensor, 10) # Same as tensor*10

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10) # Same as tensor+10

tensor([11, 12, 13])

### Matrix Multiplication
There are two main ways of doing matrix multiplicatipn in neural networks and deep learning.
1. Element wise multiplication.
2. Matrix Multiplication.

In [ ]:
  # Element wise multiplication.
  print(tensor, "*", tensor)
  print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication.
torch.matmul(tensor, tensor) # Same as: 1*1+2*2+3*3 = 14

tensor(14)

In [ ]:
# Checking time for traditional method.
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 3.02 ms, sys: 0 ns, total: 3.02 ms
Wall time: 4.5 ms


In [ ]:
# Checking time taken for torch matmul function.
%%time
torch.matmul(tensor, tensor)

CPU times: user 79 µs, sys: 1e+03 ns, total: 80 µs
Wall time: 84.4 µs


tensor(14)

### One of the most common errors in deep learning: shape errors.


In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B.T # Transposing B matrix.

tensor([[ 7,  8,  9],
        [10, 11, 12]])

To fix tensor shape issues, we can manipulate the shape of one of out tensors using a transpose.


In [ ]:
tensor_B.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed.
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimension must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutshape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimension must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Outshape: torch.Size([3, 3])


## Finding the aggregation of tensor.

In [ ]:
# Create a tensor.
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(), x.max()

(tensor(0), tensor(90))

In [ ]:
# torch.mean() requires a tensor of float32 datatype to work.
# torch.mean(x) # shows error(tensor not right datatype.)
torch.mean(x.type(torch.float32))

tensor(45.)

## Find the positional min and max.

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [ ]:
# Find the position in tensor that has the minimum value with argmax()
x.argmax()

In [ ]:
x[9]

## Reshaping, stacking, squezzing and unsqueezing in tensors.
* Reshaping - reshapes an input tensor to a defined shape.
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - Combines multiple tensors.
* Squeeze - removes all '1' dimension from a tensor.
* unsqueeze - add '1' dimension to a targer tensor.
* Permute - return a view of the input with dimension permuted(swapped) in a certain way.


In [ ]:
# Create a tensor.
import torch
x = torch.arange(1.0, 10.0)
x, x.shape

In [ ]:
# Reshape - Add an extra dimension.
# x_reshaped = x.reshape(1,7) # We are trying to squeeze 9 elements into 7 elements. Shows error.
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [ ]:
# Change the view.
z = x.view(1,9)
z, z.shape

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z,x

In [ ]:
# Stack tensors on top of each other.
x_stacked = torch.stack([x,x,x,x], dim=0) # Stacks vertically.
x_stacked

In [ ]:
# Squeeze.
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped.
x_squeezed = x_reshaped.squeeze()
print(f"\nPrevious tensor: {x_squeezed}")
print(f"\nPrevious shape: {x_squeezed.shape}")

In [ ]:
# torch.unsqueeze - adds a single dimension to a targer at a specific dimension.
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension.
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

In [ ]:
x_reshaped.shape

In [ ]:
x_reshaped.squeeze().shape

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specific order.
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis order.
x_permuted = x_original.permute(2,0,1) # Shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
# Index on new tensor.
x[0]

In [ ]:
# Index on the middle bracket (dim=1)
x[0][0]

In [ ]:
# Index on the most inner bracket (last dim)
x[0][0][0]

In [ ]:
x[0][0][2]

In [ ]:
x[0][2][2]

In [ ]:
# We can use ":" to select 'all' of a target dimension.
x[:, 0]

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension.
x[:, :, 1]

In [ ]:
# Get all values of 0th dimension but only index 1st and 2nd dimension.
x[:, 1, 1]

In [ ]:
# Get index 0 of 0th and 1st dimension but all values of 2nd dimension.
x[:, 0, :]

In [ ]:
x[:,2,:]

In [ ]:
x[:, 1, 2]

## PyTorch and NumPy

In [ ]:
# Numpy array to tensor.
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

In [ ]:
array.dtype # float64 is default numpy data type. if we go from numpy to tensor unless specified otherwise.

In [ ]:
torch.arange(1.0,8.0).dtype

In [ ]:
# Change the value of array. What will this do to tensor?
array = array+1
array, tensor # Changing array wont change tensor.

In [ ]:
# Tensor to NumPy array.
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor # Remains same.

## Reproducibility.(Trying to take random out of random)

In short how neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors.
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

Making the above thing reproducible.

In [ ]:
# Making some random but reproducible tensors.
import torch

# Set the random seed.
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

## Running tensors and PyTorch objects on the GPUs (and making faster computations)


### 1. Getting a GPU.

- Use google collab for a faster GPU.
- Use your own GPU. `learn more..`
https://timdettmers.com/
- Use could computing - Google Cloud Platform, AZURE, AWS. these services allow us to rent computers on the cloud and access them.

For setup: https://pytorch.org/


In [ ]:
!nvidia-smi

### 2. Check if we have GPU access with PyTorch.

In [ ]:
# Check for GPU access with pytorch.
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running computer on the GPU or CPU, it's best practice to setup device agnostic code.

In [ ]:
# Setup device agnostic code. (If we dont have access to GPU, but we had before. Now we want to use the previous GPU)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the number of devices.
torch.cuda.device_count()

1

### Putting tensors and models on the GPU.

- Using GPU results in faster computations.

In [ ]:
# Create a tensor(default CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU.

In [ ]:
# If tensor is on GPU, can't transform it to NumPy.
# tensor_on_gpu.numpy()  # Shows error. Numpy doesnt work with GPU.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU.
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu # Remains unchanged.

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum