# Numpy:
Numpy is a package. Which provides a multidimensional array object. Numpy array,
- Multiple types of data types can be used in Python List. Where, only single data type
  is used. 
- Consumes less memory.
- fast compared to the Python list. Because List requires a lot more space.
- Datas in list are stored in memory in a scatter manner. Containing pointers to the actual
  information that's scattered around computer memory. But in case of Numpy, informations
  are stored in memory contiguously.
- We can use SIMD Vector Processing. We can do computations on all the values at a time in
  Numpy, but in List the computations are done one by one at a time.
- Effective Cache Utilization.

### Importance:
- Provides high level mathematical functions.
- We can do mathematical, logical, sorting, shaping, selecting, Fourier Transform, Linear
  Algebra, Statiscal Operations, Simulation and more.

### Difference:
1. In Python Lists, a = [1,2,3] * b = [5,6,7] can't be done.
2. But in Numpy, a = [1,2,3] * b = [5,6,7] can be done.

# Load Numpy.

In [1]:
import numpy as np

# Basics

In [2]:
x = np.array([1,3,4])
print(x)
x

[1 3 4]


array([1, 3, 4])

In [3]:
# 2 Dimensional
y = np.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
x.ndim

1

In [5]:
y.ndim

2

In [6]:
# Memory consumed, see data type.
# It stores int32 by default.
x.dtype

dtype('int32')

In [7]:
# We can specify the data type.
x = np.array([11,22,33], dtype='int16')
x.dtype

dtype('int16')

In [8]:
# Get size
x.itemsize  #2 bytes bcz int16.

2

In [9]:
y.itemsize #2 bytes bcz int32.

4

In [10]:
# Get total number of elements.
x.size

3

In [11]:
y.size

8

In [12]:
# Get total size.
y.size * y.itemsize

32

In [13]:
y.nbytes

32

# Accessing.

In [14]:
a = np.array([[1,2,3,4,5,6,7],[11,22,33,44,55,66,77]])
print(a)

[[ 1  2  3  4  5  6  7]
 [11 22 33 44 55 66 77]]


In [71]:
# We can index with a list.
test = np.array([1,2,3,4,5,6,7,8,9])
test[[1,2,8]]

array([2, 3, 9])

In [15]:
# Get a specific element. [r, c]
a[1, 5]

66

In [16]:
a[1, -2]

66

In [17]:
# Get spcific row.
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# Get specific column.
a[:, 2]

array([ 3, 33])

In [19]:
# Getting numbers in between a range. [startindex:endindex:steps]
a[0, 1:6:2]

array([2, 4, 6])

In [20]:
# Setting new value.
a[0, 4] = 69
print(a)

[[ 1  2  3  4 69  6  7]
 [11 22 33 44 55 66 77]]


In [21]:
# Setting value for an entire column.
a[:, 2]=5
print(a)

[[ 1  2  5  4 69  6  7]
 [11 22  5 44 55 66 77]]


In [22]:
a[:,2] = [100,200]
print(a)

[[  1   2 100   4  69   6   7]
 [ 11  22 200  44  55  66  77]]


#### 3D example.

In [23]:
# (depth, rows, columns)
b = np.array([[[1,2],[3,4]],[[5,6],[8,9]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [8 9]]]


In [24]:
# Get specific element.
b[0,1,1]

4

In [25]:
# Replacing.
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays.

In [26]:
# All zero matrix.
np.zeros(5) #1D
np.zeros((3,2)) #2D
# np.zeros((2,3,3)) #3D
# np.zeros((2,3,4,2)) #4D

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
# All 1s matrix.
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [28]:
# Any other numbers.
np.full((2,3), 69, dtype='float32')

array([[69., 69., 69.],
       [69., 69., 69.]], dtype=float32)

In [29]:
# Any other nummber (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers.
np.random.rand(4,2)

array([[0.89355944, 0.84994467],
       [0.36407369, 0.18563333],
       [0.89443062, 0.9738993 ],
       [0.35232513, 0.124343  ]])

In [31]:
np.random.random_sample(a.shape)

array([[0.20698911, 0.81001363, 0.33796824, 0.48331789, 0.99707838,
        0.19186301, 0.86935138],
       [0.82860293, 0.58362293, 0.72001402, 0.45449744, 0.72904287,
        0.39729193, 0.03623116]])

In [32]:
# Random Integer Values.
np.random.randint(1,7, size=(3,3))

array([[1, 5, 1],
       [5, 4, 4],
       [6, 1, 6]])

In [33]:
# Identity matrix.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeat an array.
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Exercise 1

In [35]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays.

In [36]:
c = np.array([1,2,3])
d = c
d[0] = 100
print(d)
print(c) # it should be [1,2,3] not [100,2,3]

[100   2   3]
[100   2   3]


In [37]:
# Overcome the issue.
c = np.array([1,2,3])
d = c.copy()
d[0] = 100
print(d)
print(c)

[100   2   3]
[1 2 3]


# Mathematics.

In [38]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [39]:
a+2

array([3, 4, 5, 6])

In [40]:
a-2

array([-1,  0,  1,  2])

In [41]:
a*3

array([ 3,  6,  9, 12])

In [42]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [43]:
b = np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [44]:
a+b

array([2, 2, 4, 4])

In [45]:
a**2

array([ 1,  4,  9, 16])

In [46]:
# Sine function.
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### For more, 
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html
https://numpy.org/doc/stable/reference/routines.array-creation.html
https://numpy.org/doc/stable/reference/routines.math.html
https://numpy.org/doc/stable/reference/routines.linalg.html

## Linear Algebra

In [48]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [49]:
# Multiplication. func: 'matmul'
d = np.matmul(a,b)
print(d)

[[6. 6.]
 [6. 6.]]


In [50]:
# Determinant.
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics.

In [51]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.min(stats)

1

In [53]:
np.max(stats, axis=1)

array([4, 8])

In [54]:
np.sum(stats, axis=0)

array([ 6,  8, 10, 12])

# Reorganizing array.

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [56]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [57]:
# Vertically stacking vectors.
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
np.vstack([v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
# Horizontal stacking.
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous.

## Load Data from file.

In [65]:
file_data = np.genfromtxt('data.txt', delimiter=',').astype('int32')  #astype just makes a copy.
file_data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and advanced indexing.

In [68]:
file_data >= 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [70]:
file_data[file_data > 50] # Get only the values.

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [72]:
np.any(file_data>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [75]:
~(file_data>50) & (file_data<100)

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [76]:
(file_data>50) & (file_data<100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

# Exercise 2:

In [79]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],
               [11,12,13,14,15],[16,17,18,19,20],
               [21,22,23,24,25],[26,27,28,29,30]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [80]:
# Find 11,12,16,17
arr[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [81]:
# Find 2,8,14,20
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [84]:
# Find 4,5,24,25,29,30
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])